# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 01:43
from __future__ import unicode_literals

from django.db import migrations, models

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('orderList', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('dob', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('ssn', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=40)),
                ('task_description', models.CharField(max_length=40)),
                ('cost', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40)),
                ('outputs', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ],
        ),
        migrations.CreateModel(
            name='All_Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=40)),
                ('user_id', models.CharField(max_length=40)),
                ('task_description', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ('costs', models.CharField(max_length=40)),
                ('submitted_values', models.CharField(max_length=40)),
                ],
        ),
    ]
